import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Basic UI
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'edit': 'Editar',
    'add': 'Adicionar',
    'remove': 'Remover',
    'close': 'Fechar',
    'done': 'Concluído',
    'back': 'Voltar',
    'next': 'Próximo',
    'previous': 'Anterior',
    'confirm': 'Confirmar',
    'language': 'pt',
    'yes': 'Sim',
    'no': 'Não',
    'ok': 'OK',
    'loading': 'Carregando...',
    'error': 'Erro',
    'success': 'Sucesso',
    'warning': 'Aviso',
    'info': 'Informação',
    'retry': 'Tentar novamente',
    'skip': 'Pular',
    'continue': 'Continuar',
    'finish': 'Finalizar',
    'create': 'Criar',
    'update': 'Atualizar',
    'draft': 'Rascunho',
    'version': 'Versão',
    'settings': 'Configurações',
    'help': 'Ajuda',
    'about': 'Sobre',
    'privacy': 'Privacidade',
    'terms': 'Termos',
    'support': 'Suporte',

    // App specific
    'quicklist': 'QuickList',
    'tasks': 'Tarefas',
    'lists': 'Listas',
    'categories': 'Categorias',
    'tags': 'Tags',
    'notes': 'Notas',
    'projects': 'Projetos',
    'goals': 'Objetivos',
    'reminders': 'Lembretes',
    'deadlines': 'Prazos',
    'priority': 'Prioridade',
    'status': 'Status',
    'progress': 'Progresso',
    'completed': 'Concluído',
    'pending': 'Pendente',
    'archived': 'Arquivado',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'public': 'Público',
    'private': 'Privado',
    'shared': 'Compartilhado',
    'personal': 'Pessoal',
    'work': 'Trabalho',
    'home': 'Casa',
    'family': 'Família',
    'friends': 'Amigos',
    'health': 'Saúde',
    'fitness': 'Fitness',
    'education': 'Educação',
    'hobbies': 'Hobbies',
    'travel': 'Viagem',
    'shopping': 'Compras',
    'finance': 'Finanças',
    'business': 'Negócios',
    'technology': 'Tecnologia',
    'entertainment': 'Entretenimento',
    'food': 'Comida',
    'other': 'Outro',

    // List management
    'myLists': 'Minhas Listas',
    'newList': 'Nova Lista',
    'editList': 'Editar Lista',
    'deleteList': 'Excluir Lista',
    'duplicateList': 'Duplicar Lista',
    'shareList': 'Compartilhar Lista',
    'exportList': 'Exportar Lista',
    'importList': 'Importar Lista',
    'listTitle': 'Título da Lista',
    'listDescription': 'Descrição da Lista',
    'listColor': 'Cor da Lista',
    'listIcon': 'Ícone da Lista',
    'listItems': 'Itens da Lista',
    'listCategories': 'Categorias da Lista',
    'listTags': 'Tags da Lista',
    'listSettings': 'Configurações da Lista',
    'listStats': 'Estatísticas da Lista',
    'listHistory': 'Histórico da Lista',
    'listMembers': 'Membros da Lista',
    'listPermissions': 'Permissões da Lista',
    'listNotifications': 'Notificações da Lista',
    'listReminders': 'Lembretes da Lista',
    'listDeadlines': 'Prazos da Lista',
    'listPriority': 'Prioridade da Lista',
    'listProgress': 'Progresso da Lista',
    'listCompletion': 'Conclusão da Lista',
    'listCreated': 'Lista criada',
    'listUpdated': 'Lista atualizada',
    'listDeleted': 'Lista excluída',
    'listArchived': 'Lista arquivada',
    'listRestored': 'Lista restaurada',
    'listShared': 'Lista compartilhada',
    'listExported': 'Lista exportada',
    'listImported': 'Lista importada',
    'listDuplicated': 'Lista duplicada',
    'listItems.placeholder': 'Digite um novo item...',

    // Item management
    'newItem': 'Novo Item',
    'editItem': 'Editar Item',
    'deleteItem': 'Excluir Item',
    'duplicateItem': 'Duplicar Item',
    'moveItem': 'Mover Item',
    'copyItem': 'Copiar Item',
    'itemTitle': 'Título do Item',
    'itemDescription': 'Descrição do Item',
    'itemNotes': 'Notas do Item',
    'itemTags': 'Tags do Item',
    'itemCategory': 'Categoria do Item',
    'itemPriority': 'Prioridade do Item',
    'itemStatus': 'Status do Item',
    'itemDeadline': 'Prazo do Item',
    'itemReminder': 'Lembrete do Item',
    'itemProgress': 'Progresso do Item',
    'itemCompletion': 'Conclusão do Item',
    'itemCreated': 'Item criado',
    'itemUpdated': 'Item atualizado',
    'itemDeleted': 'Item excluído',
    'itemCompleted': 'Item concluído',
    'itemUncompleted': 'Item não concluído',
    'itemArchived': 'Item arquivado',
    'itemRestored': 'Item restaurado',
    'itemMoved': 'Item movido',
    'itemCopied': 'Item copiado',
    'itemDuplicated': 'Item duplicado',

    // Categories
    'newCategory': 'Nova Categoria',
    'editCategory': 'Editar Categoria',
    'deleteCategory': 'Excluir Categoria',
    'categoryName': 'Nome da Categoria',
    'categoryDescription': 'Descrição da Categoria',
    'categoryColor': 'Cor da Categoria',
    'categoryIcon': 'Ícone da Categoria',
    'categoryCreated': 'Categoria criada',
    'categoryUpdated': 'Categoria atualizada',
    'categoryDeleted': 'Categoria excluída',

    // Search and filtering
    'searchLists': 'Buscar listas',
    'showArchived': 'Mostrar arquivadas',
    'filters': 'Filtros',
    'allLists': 'Todas as Listas',
    'search': 'Buscar',
    'search.placeholder': 'Buscar listas...',
    'filter': 'Filtrar',
    'filterBy': 'Filtrar por',
    'filterByCategory': 'Filtrar por categoria',
    'filterByTag': 'Filtrar por tag',
    'filterByStatus': 'Filtrar por status',
    'filterByPriority': 'Filtrar por prioridade',
    'filterByDate': 'Filtrar por data',
    'sortBy': 'Ordenar por',
    'sortByName': 'Ordenar por nome',
    'sortByDate': 'Ordenar por data',
    'sortByPriority': 'Ordenar por prioridade',
    'sortByStatus': 'Ordenar por status',
    'sortByCompletion': 'Ordenar por conclusão',
    'groupBy': 'Agrupar por',
    'groupByCategory': 'Agrupar por categoria',
    'groupByTag': 'Agrupar por tag',
    'groupByStatus': 'Agrupar por status',
    'groupByPriority': 'Agrupar por prioridade',
    'groupByDate': 'Agrupar por data',

    // Empty states
    'noLists': 'Nenhuma lista encontrada',
    'noListsDesc': 'Crie sua primeira lista para começar a organizar suas tarefas.',
    'noItems': 'Nenhum item',
    'noItemsDesc': 'Adicione itens à sua lista para começar.',
    'noCategories': 'Nenhuma categoria encontrada',
    'noCategoriesDesc': 'Crie categorias para organizar suas listas.',
    'noTags': 'Nenhuma tag encontrada',
    'noTagsDesc': 'Adicione tags para categorizar seus itens.',
    'noResults': 'Nenhum resultado encontrado',
    'noResultsDesc': 'Tente ajustar seus filtros ou termo de busca.',
    'listPlaceholder': 'Nome da nova lista...',
    'createFirstList': 'Criar primeira lista',
    'newListName': 'Nome da nova lista',
    'typeItem': 'Digite um item...',
    'addList': 'Criar Lista',
    'createNewList': 'Criar Nova Lista',
    'createNewListForm': 'Formulário para criar nova lista',
    'chooseListColor': 'Escolher cor da lista',
    'placeholder': 'Digite aqui...',
    'addItemHere': 'Adicionar item aqui',

    // Onboarding Portuguese
    'onboarding.welcome.title': 'Bem-vindo ao QuickList!',
    'onboarding.welcome.description': 'Vamos começar criando sua primeira lista de tarefas.',
    'onboarding.features.title': 'Recursos Principais',
    'onboarding.features.description': 'Organize suas tarefas, defina prioridades e acompanhe seu progresso.',
    'onboarding.templates.title': 'Use Modelos',
    'onboarding.templates.description': 'Comece rapidamente com nossos modelos predefinidos.',
    'onboarding.start': 'Começar',
    'onboarding.skip': 'Pular',
    'onboarding.next': 'Próximo',
    'onboarding.back': 'Voltar',
    'onboarding.finish': 'Finalizar',

    // Templates
    'templates': 'Modelos',
    'useTemplate': 'Usar Modelo',
    'personalTemplate': 'Pessoal',
    'personalDesc': 'Lista pessoal para tarefas diárias',
    'personalItems': 'Verificar emails, Exercitar-se, Planejar fim de semana',
    'workTemplate': 'Trabalho', 
    'workDesc': 'Lista de trabalho para produtividade',
    'workItems': 'Reunião de equipe, Revisar relatórios, Responder emails',
    'shoppingTemplate': 'Compras',
    'shoppingDesc': 'Lista de compras para o supermercado',
    'shoppingItems': 'Leite, Pão, Frutas',
    'travelTemplate': 'Viagem',
    'travelDesc': 'Lista de viagem e preparativos',
    'travelItems': 'Passaporte, Roupas, Câmera',

    // Auth
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Criar Conta',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.passwordMin': 'Senha (mínimo 6 caracteres)',
    'auth.loginButton': 'Entrar',
    'auth.signUpButton': 'Criar Conta',
    'auth.loggingIn': 'Entrando...',
    'auth.signingUp': 'Criando conta...',
    'auth.invalidCredentials': 'Credenciais inválidas',
    'auth.signUpSuccess': 'Conta criada com sucesso!',
    'auth.signInSuccess': 'Login realizado com sucesso!',
    'auth.signOutSuccess': 'Logout realizado com sucesso!',
    'auth.error': 'Erro de autenticação',

    // Sticky Notes
    'notes.title': 'Notas Adesivas',
    'notes.newNote': 'Nova Nota',
    'notes.editNote': 'Editar Nota',
    'notes.deleteNote': 'Excluir Nota',
    'notes.duplicateNote': 'Duplicar Nota',
    'notes.shareNote': 'Compartilhar Nota',
    'notes.exportNote': 'Exportar Nota',
    'notes.searchNotes': 'Buscar notas...',
    'notes.noNotes': 'Nenhuma nota encontrada',
    'notes.noNotesDesc': 'Crie sua primeira nota para começar.',
    'notes.noteTitle': 'Título da Nota',
    'notes.noteContent': 'Conteúdo da Nota',
    'notes.searchPlaceholder': 'Buscar notas...',
    'notes.noNotesCreate': 'Criar primeira nota',
    'notes.color': 'Cor',
    'notes.colorLabel': 'Cor da Nota',
    'notes.titleLabel': 'Título',
    'notes.contentLabel': 'Conteúdo',
    'notes.titlePlaceholder': 'Digite o título da nota...',
    'notes.contentPlaceholder': 'Escreva sua nota...',
    'notes.cancel': 'Cancelar',
    'notes.saveChanges': 'Salvar Alterações',
    'notes.delete': 'Excluir',
    
    // Statistics
    'stats.title': 'Estatísticas',
    'stats.overview': 'Visão Geral',
    'stats.productivity': 'Produtividade',
    'stats.trends': 'Tendências',
    'stats.insights': 'Insights',
    'stats.totalTasks': 'Total de Tarefas',
    'stats.completedTasks': 'Tarefas Concluídas',
    'stats.pendingTasks': 'Tarefas Pendentes',
    'stats.completionRate': 'Taxa de Conclusão',
    'stats.averageCompletion': 'Conclusão Média',
    'stats.mostProductiveDay': 'Dia Mais Produtivo',
    'stats.streak': 'Sequência',
    'stats.currentStreak': 'Sequência Atual',
    'stats.longestStreak': 'Maior Sequência',
    'stats.dailyAverage': 'Média Diária',
    'stats.weeklyAverage': 'Média Semanal',
    'stats.monthlyAverage': 'Média Mensal',
    'stats.categories': 'Categorias',
    'stats.topCategories': 'Principais Categorias',
    'stats.recentActivity': 'Atividade Recente',
    'stats.noData': 'Nenhum dado disponível',
    'stats.noDataDesc': 'Complete algumas tarefas para ver suas estatísticas.',

    // Achievements
    'achievements.title': 'Conquistas',
    'achievements.unlocked': 'Desbloqueadas',
    'achievements.locked': 'Bloqueadas',
    'achievements.progress': 'Progresso',
    'achievements.recent': 'Recentes',
    'achievements.all': 'Todas',
    'achievements.category': 'Categoria',
    'achievements.difficulty': 'Dificuldade',
    'achievements.rarity': 'Raridade',
    'achievements.points': 'Pontos',
    'achievements.level': 'Nível',
    'achievements.experience': 'Experiência',
    'achievements.nextLevel': 'Próximo Nível',
    'achievements.unlockNext': 'Próxima a Desbloquear',
    'achievements.congratulations': 'Parabéns!',
    'achievements.unlockMessage': 'Você desbloqueou uma nova conquista!',
    'achievements.share': 'Compartilhar Conquista',
    'achievements.noAchievements': 'Nenhuma conquista desbloqueada',
    'achievements.noAchievementsDesc': 'Complete tarefas para desbloquear conquistas.',

    // Notifications
    'notifications.title': 'Notificações',
    'notifications.enable': 'Habilitar Notificações',
    'notifications.disable': 'Desabilitar Notificações',
    'notifications.permission': 'Permissão de Notificação',
    'notifications.permissionDesc': 'Permita notificações para receber lembretes.',
    'notifications.settings': 'Configurações de Notificação',
    'notifications.daily': 'Notificações Diárias',
    'notifications.reminders': 'Lembretes',
    'notifications.achievements': 'Conquistas',
    'notifications.updates': 'Atualizações',
    'notifications.marketing': 'Marketing',
    'notifications.sound': 'Som',
    'notifications.vibration': 'Vibração',
    'notifications.time': 'Horário',
    'notifications.frequency': 'Frequência',
    'notifications.test': 'Testar Notificação',

    // Accessibility
    'accessibility.label': 'Rótulo de Acessibilidade',
    'accessibility.description': 'Descrição de Acessibilidade',
    'accessibility.role': 'Função',
    'accessibility.state': 'Estado',
    'accessibility.properties': 'Propriedades',
    'accessibility.keyboard': 'Navegação por Teclado',
    'accessibility.screenReader': 'Leitor de Tela',
    'accessibility.highContrast': 'Alto Contraste',
    'accessibility.fontSize': 'Tamanho da Fonte',
    'accessibility.colorBlind': 'Daltonismo',
    'accessibility.motionReduced': 'Movimento Reduzido',

    // Performance
    'performance.loading': 'Carregando...',
    'performance.loadingTime': 'Tempo de Carregamento',
    'performance.renderTime': 'Tempo de Renderização',
    'performance.memoryUsage': 'Uso de Memória',
    'performance.cacheSize': 'Tamanho do Cache',
    'performance.networkSpeed': 'Velocidade da Rede',
    'performance.offline': 'Offline',
    'performance.online': 'Online',
    'performance.sync': 'Sincronização',
    'performance.backup': 'Backup',
    'performance.restore': 'Restaurar',

    // Errors
    'error.generic': 'Ocorreu um erro',
    'error.network': 'Erro de rede',
    'error.server': 'Erro do servidor',
    'error.client': 'Erro do cliente',
    'error.validation': 'Erro de validação',
    'error.authentication': 'Erro de autenticação',
    'error.authorization': 'Erro de autorização',
    'error.notFound': 'Não encontrado',
    'error.timeout': 'Tempo esgotado',
    'error.offline': 'Sem conexão',
    'error.storage': 'Erro de armazenamento',
    'error.permission': 'Erro de permissão',
    'error.browser': 'Erro do navegador',
    'error.javascript': 'Erro de JavaScript',
    'error.unknown': 'Erro desconhecido',

    // Success messages
    'success.saved': 'Salvo com sucesso',
    'success.deleted': 'Excluído com sucesso',
    'success.created': 'Criado com sucesso',
    'success.updated': 'Atualizado com sucesso',
    'success.completed': 'Concluído com sucesso',
    'success.shared': 'Compartilhado com sucesso',
    'success.exported': 'Exportado com sucesso',
    'success.imported': 'Importado com sucesso',
    'success.synced': 'Sincronizado com sucesso',
    'success.backup': 'Backup realizado com sucesso',
    'success.restore': 'Restaurado com sucesso',

    // Time and dates
    'time.now': 'Agora',
    'time.today': 'Hoje',
    'time.yesterday': 'Ontem',
    'time.tomorrow': 'Amanhã',
    'time.thisWeek': 'Esta semana',
    'time.lastWeek': 'Semana passada',
    'time.nextWeek': 'Próxima semana',
    'time.thisMonth': 'Este mês',
    'time.lastMonth': 'Mês passado',
    'time.nextMonth': 'Próximo mês',
    'time.thisYear': 'Este ano',
    'time.lastYear': 'Ano passado',
    'time.nextYear': 'Próximo ano',
    'time.second': 'segundo',
    'time.seconds': 'segundos',
    'time.minute': 'minuto',
    'time.minutes': 'minutos',
    'time.hour': 'hora',
    'time.hours': 'horas',
    'time.day': 'dia',
    'time.days': 'dias',
    'time.week': 'semana',
    'time.weeks': 'semanas',
    'time.month': 'mês',
    'time.months': 'meses',
    'time.year': 'ano',
    'time.years': 'anos',
    'time.ago': 'atrás',
    'time.in': 'em',
    'time.at': 'às',
    'time.on': 'em',
    'time.from': 'de',
    'time.to': 'até',
    'time.until': 'até',
    'time.since': 'desde',
    'time.duration': 'duração',
    'time.start': 'início',
    'time.end': 'fim',
    'time.deadline': 'prazo',
    'time.reminder': 'lembrete',
    'time.overdue': 'atrasado',
    'time.upcoming': 'próximo'
  },
  en: {
    // Basic UI
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'remove': 'Remove',
    'close': 'Close',
    'done': 'Done',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'confirm': 'Confirm',
    'language': 'en',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'retry': 'Retry',
    'skip': 'Skip',
    'continue': 'Continue',
    'finish': 'Finish',
    'create': 'Create',
    'update': 'Update',
    'draft': 'Draft',
    'version': 'Version',
    'settings': 'Settings',
    'help': 'Help',
    'about': 'About',
    'privacy': 'Privacy',
    'terms': 'Terms',
    'support': 'Support',

    // App specific
    'quicklist': 'QuickList',
    'tasks': 'Tasks',
    'lists': 'Lists',
    'categories': 'Categories',
    'tags': 'Tags',
    'notes': 'Notes',
    'projects': 'Projects',
    'goals': 'Goals',
    'reminders': 'Reminders',
    'deadlines': 'Deadlines',
    'priority': 'Priority',
    'status': 'Status',
    'progress': 'Progress',
    'completed': 'Completed',
    'pending': 'Pending',
    'archived': 'Archived',
    'active': 'Active',
    'inactive': 'Inactive',
    'public': 'Public',
    'private': 'Private',
    'shared': 'Shared',
    'personal': 'Personal',
    'work': 'Work',
    'home': 'Home',
    'family': 'Family',
    'friends': 'Friends',
    'health': 'Health',
    'fitness': 'Fitness',
    'education': 'Education',
    'hobbies': 'Hobbies',
    'travel': 'Travel',
    'shopping': 'Shopping',
    'finance': 'Finance',
    'business': 'Business',
    'technology': 'Technology',
    'entertainment': 'Entertainment',
    'food': 'Food',
    'other': 'Other',

    // List management
    'myLists': 'My Lists',
    'newList': 'New List',
    'editList': 'Edit List',
    'deleteList': 'Delete List',
    'duplicateList': 'Duplicate List',
    'shareList': 'Share List',
    'exportList': 'Export List',
    'importList': 'Import List',
    'listTitle': 'List Title',
    'listDescription': 'List Description',
    'listColor': 'List Color',
    'listIcon': 'List Icon',
    'listItems': 'List Items',
    'listCategories': 'List Categories',
    'listTags': 'List Tags',
    'listSettings': 'List Settings',
    'listStats': 'List Statistics',
    'listHistory': 'List History',
    'listMembers': 'List Members',
    'listPermissions': 'List Permissions',
    'listNotifications': 'List Notifications',
    'listReminders': 'List Reminders',
    'listDeadlines': 'List Deadlines',
    'listPriority': 'List Priority',
    'listProgress': 'List Progress',
    'listCompletion': 'List Completion',
    'listCreated': 'List created',
    'listUpdated': 'List updated',
    'listDeleted': 'List deleted',
    'listArchived': 'List archived',
    'listRestored': 'List restored',
    'listShared': 'List shared',
    'listExported': 'List exported',
    'listImported': 'List imported',
    'listDuplicated': 'List duplicated',
    'listItems.placeholder': 'Type a new item...',

    // Item management
    'newItem': 'New Item',
    'editItem': 'Edit Item',
    'deleteItem': 'Delete Item',
    'duplicateItem': 'Duplicate Item',
    'moveItem': 'Move Item',
    'copyItem': 'Copy Item',
    'itemTitle': 'Item Title',
    'itemDescription': 'Item Description',
    'itemNotes': 'Item Notes',
    'itemTags': 'Item Tags',
    'itemCategory': 'Item Category',
    'itemPriority': 'Item Priority',
    'itemStatus': 'Item Status',
    'itemDeadline': 'Item Deadline',
    'itemReminder': 'Item Reminder',
    'itemProgress': 'Item Progress',
    'itemCompletion': 'Item Completion',
    'itemCreated': 'Item created',
    'itemUpdated': 'Item updated',
    'itemDeleted': 'Item deleted',
    'itemCompleted': 'Item completed',
    'itemUncompleted': 'Item uncompleted',
    'itemArchived': 'Item archived',
    'itemRestored': 'Item restored',
    'itemMoved': 'Item moved',
    'itemCopied': 'Item copied',
    'itemDuplicated': 'Item duplicated',

    // Categories
    'newCategory': 'New Category',
    'editCategory': 'Edit Category',
    'deleteCategory': 'Delete Category',
    'categoryName': 'Category Name',
    'categoryDescription': 'Category Description',
    'categoryColor': 'Category Color',
    'categoryIcon': 'Category Icon',
    'categoryCreated': 'Category created',
    'categoryUpdated': 'Category updated',
    'categoryDeleted': 'Category deleted',

    // Search and filtering
    'searchLists': 'Search lists',
    'showArchived': 'Show archived',
    'filters': 'Filters',
    'allLists': 'All Lists',
    'search': 'Search',
    'search.placeholder': 'Search lists...',
    'filter': 'Filter',
    'filterBy': 'Filter by',
    'filterByCategory': 'Filter by category',
    'filterByTag': 'Filter by tag',
    'filterByStatus': 'Filter by status',
    'filterByPriority': 'Filter by priority',
    'filterByDate': 'Filter by date',
    'sortBy': 'Sort by',
    'sortByName': 'Sort by name',
    'sortByDate': 'Sort by date',
    'sortByPriority': 'Sort by priority',
    'sortByStatus': 'Sort by status',
    'sortByCompletion': 'Sort by completion',
    'groupBy': 'Group by',
    'groupByCategory': 'Group by category',
    'groupByTag': 'Group by tag',
    'groupByStatus': 'Group by status',
    'groupByPriority': 'Group by priority',
    'groupByDate': 'Group by date',

    // Empty states
    'noLists': 'No lists found',
    'noListsDesc': 'Create your first list to start organizing your tasks.',
    'noItems': 'No items',
    'noItemsDesc': 'Add items to your list to get started.',
    'noCategories': 'No categories found',
    'noCategoriesDesc': 'Create categories to organize your lists.',
    'noTags': 'No tags found',
    'noTagsDesc': 'Add tags to categorize your items.',
    'noResults': 'No results found',
    'noResultsDesc': 'Try adjusting your filters or search term.',
    'listPlaceholder': 'New list name...',
    'createFirstList': 'Create first list',
    'newListName': 'New list name',
    'typeItem': 'Type item...',
    'addList': 'Create List',
    'createNewList': 'Create New List',
    'createNewListForm': 'Form to create new list',
    'chooseListColor': 'Choose list color',
    'placeholder': 'Type here...',
    'addItemHere': 'Add item here',

    // Onboarding
    'onboarding.welcome.title': 'Welcome to QuickList!',
    'onboarding.welcome.description': 'Let\'s get started by creating your first task list.',
    'onboarding.features.title': 'Key Features',
    'onboarding.features.description': 'Organize your tasks, set priorities, and track your progress.',
    'onboarding.templates.title': 'Use Templates',
    'onboarding.templates.description': 'Get started quickly with our predefined templates.',
    'onboarding.start': 'Get Started',
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.back': 'Back',
    'onboarding.finish': 'Finish',

    // Templates
    'templates': 'Templates',
    'useTemplate': 'Use Template',
    'personalTemplate': 'Personal',
    'personalDesc': 'Personal list for daily tasks',
    'personalItems': 'Check emails, Exercise, Plan weekend',
    'workTemplate': 'Work',
    'workDesc': 'Work list for productivity',
    'workItems': 'Team meeting, Review reports, Reply emails',
    'shoppingTemplate': 'Shopping',
    'shoppingDesc': 'Shopping list for groceries',
    'shoppingItems': 'Milk, Bread, Fruits',
    'travelTemplate': 'Travel',
    'travelDesc': 'Travel list and preparations',
    'travelItems': 'Passport, Clothes, Camera',

    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.passwordMin': 'Password (minimum 6 characters)',
    'auth.loginButton': 'Sign In',
    'auth.signUpButton': 'Sign Up',
    'auth.loggingIn': 'Signing in...',
    'auth.signingUp': 'Creating account...',
    'auth.invalidCredentials': 'Invalid credentials',
    'auth.signUpSuccess': 'Account created successfully!',
    'auth.signInSuccess': 'Signed in successfully!',
    'auth.signOutSuccess': 'Signed out successfully!',
    'auth.error': 'Authentication error',

    // Sticky Notes
    'notes.title': 'Sticky Notes',
    'notes.newNote': 'New Note',
    'notes.editNote': 'Edit Note',
    'notes.deleteNote': 'Delete Note',
    'notes.duplicateNote': 'Duplicate Note',
    'notes.shareNote': 'Share Note',
    'notes.exportNote': 'Export Note',
    'notes.searchNotes': 'Search notes...',
    'notes.noNotes': 'No notes found',
    'notes.noNotesDesc': 'Create your first note to get started.',
    'notes.noteTitle': 'Note Title',
    'notes.noteContent': 'Note Content',
    'notes.searchPlaceholder': 'Search notes...',
    'notes.noNotesCreate': 'Create first note',
    'notes.color': 'Color',
    'notes.colorLabel': 'Note Color',
    'notes.titleLabel': 'Title',
    'notes.contentLabel': 'Content',
    'notes.titlePlaceholder': 'Enter note title...',
    'notes.contentPlaceholder': 'Write your note...',
    'notes.cancel': 'Cancel',
    'notes.saveChanges': 'Save Changes',
    'notes.delete': 'Delete',
    
    // Statistics
    'stats.title': 'Statistics',
    'stats.overview': 'Overview',
    'stats.productivity': 'Productivity',
    'stats.trends': 'Trends',
    'stats.insights': 'Insights',
    'stats.totalTasks': 'Total Tasks',
    'stats.completedTasks': 'Completed Tasks',
    'stats.pendingTasks': 'Pending Tasks',
    'stats.completionRate': 'Completion Rate',
    'stats.averageCompletion': 'Average Completion',
    'stats.mostProductiveDay': 'Most Productive Day',
    'stats.streak': 'Streak',
    'stats.currentStreak': 'Current Streak',
    'stats.longestStreak': 'Longest Streak',
    'stats.dailyAverage': 'Daily Average',
    'stats.weeklyAverage': 'Weekly Average',
    'stats.monthlyAverage': 'Monthly Average',
    'stats.categories': 'Categories',
    'stats.topCategories': 'Top Categories',
    'stats.recentActivity': 'Recent Activity',
    'stats.noData': 'No data available',
    'stats.noDataDesc': 'Complete some tasks to see your statistics.',

    // Achievements
    'achievements.title': 'Achievements',
    'achievements.unlocked': 'Unlocked',
    'achievements.locked': 'Locked',
    'achievements.progress': 'Progress',
    'achievements.recent': 'Recent',
    'achievements.all': 'All',
    'achievements.category': 'Category',
    'achievements.difficulty': 'Difficulty',
    'achievements.rarity': 'Rarity',
    'achievements.points': 'Points',
    'achievements.level': 'Level',
    'achievements.experience': 'Experience',
    'achievements.nextLevel': 'Next Level',
    'achievements.unlockNext': 'Next to Unlock',
    'achievements.congratulations': 'Congratulations!',
    'achievements.unlockMessage': 'You unlocked a new achievement!',
    'achievements.share': 'Share Achievement',
    'achievements.noAchievements': 'No achievements unlocked',
    'achievements.noAchievementsDesc': 'Complete tasks to unlock achievements.',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.enable': 'Enable Notifications',
    'notifications.disable': 'Disable Notifications',
    'notifications.permission': 'Notification Permission',
    'notifications.permissionDesc': 'Allow notifications to receive reminders.',
    'notifications.settings': 'Notification Settings',
    'notifications.daily': 'Daily Notifications',
    'notifications.reminders': 'Reminders',
    'notifications.achievements': 'Achievements',
    'notifications.updates': 'Updates',
    'notifications.marketing': 'Marketing',
    'notifications.sound': 'Sound',
    'notifications.vibration': 'Vibration',
    'notifications.time': 'Time',
    'notifications.frequency': 'Frequency',
    'notifications.test': 'Test Notification',

    // Accessibility
    'accessibility.label': 'Accessibility Label',
    'accessibility.description': 'Accessibility Description',
    'accessibility.role': 'Role',
    'accessibility.state': 'State',
    'accessibility.properties': 'Properties',
    'accessibility.keyboard': 'Keyboard Navigation',
    'accessibility.screenReader': 'Screen Reader',
    'accessibility.highContrast': 'High Contrast',
    'accessibility.fontSize': 'Font Size',
    'accessibility.colorBlind': 'Color Blind',
    'accessibility.motionReduced': 'Reduced Motion',

    // Performance
    'performance.loading': 'Loading...',
    'performance.loadingTime': 'Loading Time',
    'performance.renderTime': 'Render Time',
    'performance.memoryUsage': 'Memory Usage',
    'performance.cacheSize': 'Cache Size',
    'performance.networkSpeed': 'Network Speed',
    'performance.offline': 'Offline',
    'performance.online': 'Online',
    'performance.sync': 'Sync',
    'performance.backup': 'Backup',
    'performance.restore': 'Restore',

    // Errors
    'error.generic': 'An error occurred',
    'error.network': 'Network error',
    'error.server': 'Server error',
    'error.client': 'Client error',
    'error.validation': 'Validation error',
    'error.authentication': 'Authentication error',
    'error.authorization': 'Authorization error',
    'error.notFound': 'Not found',
    'error.timeout': 'Timeout',
    'error.offline': 'No connection',
    'error.storage': 'Storage error',
    'error.permission': 'Permission error',
    'error.browser': 'Browser error',
    'error.javascript': 'JavaScript error',
    'error.unknown': 'Unknown error',

    // Success messages
    'success.saved': 'Successfully saved',
    'success.deleted': 'Successfully deleted',
    'success.created': 'Successfully created',
    'success.updated': 'Successfully updated',
    'success.completed': 'Successfully completed',
    'success.shared': 'Successfully shared',
    'success.exported': 'Successfully exported',
    'success.imported': 'Successfully imported',
    'success.synced': 'Successfully synced',
    'success.backup': 'Successfully backed up',
    'success.restore': 'Successfully restored',

    // Time and dates
    'time.now': 'Now',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.tomorrow': 'Tomorrow',
    'time.thisWeek': 'This week',
    'time.lastWeek': 'Last week',
    'time.nextWeek': 'Next week',
    'time.thisMonth': 'This month',
    'time.lastMonth': 'Last month',
    'time.nextMonth': 'Next month',
    'time.thisYear': 'This year',
    'time.lastYear': 'Last year',
    'time.nextYear': 'Next year',
    'time.second': 'second',
    'time.seconds': 'seconds',
    'time.minute': 'minute',
    'time.minutes': 'minutes',
    'time.hour': 'hour',
    'time.hours': 'hours',
    'time.day': 'day',
    'time.days': 'days',
    'time.week': 'week',
    'time.weeks': 'weeks',
    'time.month': 'month',
    'time.months': 'months',
    'time.year': 'year',
    'time.years': 'years',
    'time.ago': 'ago',
    'time.in': 'in',
    'time.at': 'at',
    'time.on': 'on',
    'time.from': 'from',
    'time.to': 'to',
    'time.until': 'until',
    'time.since': 'since',
    'time.duration': 'duration',
    'time.start': 'start',
    'time.end': 'end',
    'time.deadline': 'deadline',
    'time.reminder': 'reminder',
    'time.overdue': 'overdue',
    'time.upcoming': 'upcoming'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem('quicklist-language');
    return stored || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('quicklist-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations] || translations.pt;
    return langTranslations[key as keyof typeof langTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};