import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Basic
    'add': 'Adicionar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'close': 'Fechar',
    'back': 'Voltar',
    'next': 'Próximo',
    'previous': 'Anterior',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'sort': 'Ordenar',
    'export': 'Exportar',
    'import': 'Importar',
    'settings': 'Configurações',
    'help': 'Ajuda',
    'about': 'Sobre',
    'loading': 'Carregando...',
    'error': 'Erro',
    'success': 'Sucesso',
    'warning': 'Aviso',
    'info': 'Informação',
    
    // App specific
    'appName': 'QuickList',
    'homescreen': 'Início',
    'allLists': 'Todas as Listas',
    'newList': 'Nova Lista',
    'createList': 'Criar Lista',
    'addList': 'Adicionar Lista',
    'editList': 'Editar Lista',
    'deleteList': 'Excluir Lista',
    'listTitle': 'Título da Lista',
    'listDescription': 'Descrição da Lista',
    'listColor': 'Cor da Lista',
    'noLists': 'Nenhuma lista criada',
    'noListsDesc': 'Crie sua primeira lista para começar a organizar suas tarefas.',
    'listNotFound': 'Lista não encontrada',
    'backToLists': 'Voltar às Listas',
    'searchLists': 'Buscar listas',
    'showArchived': 'Mostrar Arquivadas',
    'hideArchived': 'Ocultar Arquivadas',
    'archiveList': 'Arquivar Lista',
    'unarchiveList': 'Desarquivar Lista',
    'duplicateList': 'Duplicar Lista',
    'shareList': 'Compartilhar Lista',
    'listCopied': 'Lista copiada para a área de transferência',
    'linkCopied': 'Link copiado para a área de transferência',
    'listShared': 'Lista compartilhada com sucesso',
    'listUpdated': 'Lista atualizada com sucesso',
    'listCreated': 'Lista criada com sucesso',
    'listDeleted': 'Lista excluída com sucesso',
    'listArchived': 'Lista arquivada com sucesso',
    'listUnarchived': 'Lista desarquivada com sucesso',
    'listDuplicated': 'Lista duplicada com sucesso',
    
    // Items
    'addItem': 'Adicionar Item',
    'newItem': 'Novo Item',
    'editItem': 'Editar Item',
    'deleteItem': 'Excluir Item',
    'itemText': 'Texto do Item',
    'itemAdded': 'Item adicionado',
    'itemRemoved': 'Item removido',
    'itemUpdated': 'Item atualizado',
    'itemMoved': 'Item movido',
    'completedItem': '✓',
    'pendingItem': '○',
    'noItems': 'Nenhum item',
    'addItemHere': 'Adicione itens aqui...',
    'addItemPlaceholder': 'Digite o texto do item...',
    'searchTasks': 'Buscar tarefas...',
    'searchTasksPlaceholder': 'Digite para buscar...',
    'pending': 'Pendentes',
    'completed': 'Concluídas',
    'completedItemsRemoved': 'itens concluídos removidos',
    'markComplete': 'Marcar como concluído',
    'markIncomplete': 'Marcar como pendente',
    'priority': 'Prioridade',
    'dueDate': 'Data de Vencimento',
    'category': 'Categoria',
    'categories': 'Categorias',
    'notes': 'Notas',
    'filters': 'Filtros',
    'sortBy': 'Ordenar por',
    'recent': 'Recente',
    'alphabetical': 'Alfabética',
    'completedSort': 'Concluídas',
    'showCompleted': 'Mostrar concluídas',
    'hideCompleted': 'Ocultar concluídas',
    'clearCompleted': 'Limpar concluídas',
    'selectAll': 'Selecionar tudo',
    'deselectAll': 'Deselecionar tudo',
    
    // Statistics and insights
    'insights': 'Insights',
    'statistics': 'Estatísticas',
    'achievements': 'Conquistas',
    'totalLists': 'Total de Listas',
    'totalItems': 'Total de Itens',
    'completedItems': 'Itens Concluídos',
    'pendingItems': 'Itens Pendentes',
    'completionRate': 'Taxa de Conclusão',
    'productivity': 'Produtividade',
    'streak': 'Sequência',
    'longestStreak': 'Maior Sequência',
    'currentStreak': 'Sequência Atual',
    'averageCompletion': 'Conclusão Média',
    'dailyGoal': 'Meta Diária',
    'weeklyGoal': 'Meta Semanal',
    'monthlyGoal': 'Meta Mensal',
    
    // Templates
    'templates': 'Modelos',
    'useTemplate': 'Usar Modelo',
    'selectTemplate': 'Selecionar Modelo',
    'personalTemplate': 'Pessoal',
    'workTemplate': 'Trabalho',
    'shoppingTemplate': 'Compras',
    'travelTemplate': 'Viagem',
    'customTemplate': 'Personalizado',
    'templateApplied': 'Modelo aplicado com sucesso',
    
    // UI Elements
    'homeScreen': 'Tela Inicial',
    'widget': 'Widget',
    'notification': 'Notificação',
    'notifications': 'Notificações',
    'darkMode': 'Modo Escuro',
    'lightMode': 'Modo Claro',
    'language': 'Idioma',
    'theme': 'Tema',
    'profile': 'Perfil',
    'account': 'Conta',
    'login': 'Entrar',
    'logout': 'Sair',
    'signup': 'Cadastrar',
    'forgotPassword': 'Esqueci a Senha',
    'resetPassword': 'Redefinir Senha',
    'changePassword': 'Alterar Senha',
    'email': 'E-mail',
    'password': 'Senha',
    'confirmPassword': 'Confirmar Senha',
    'rememberMe': 'Lembrar de mim',
    'stayLoggedIn': 'Manter conectado',
    
    // Messages and feedback
    'welcomeMessage': 'Bem-vindo ao QuickList!',
    'errorMessage': 'Ocorreu um erro. Tente novamente.',
    'successMessage': 'Operação realizada com sucesso!',
    'confirmDelete': 'Tem certeza que deseja excluir?',
    'confirmArchive': 'Tem certeza que deseja arquivar?',
    'confirmClear': 'Tem certeza que deseja limpar todos os itens concluídos?',
    'noResultsFound': 'Nenhum resultado encontrado',
    'tryDifferentSearch': 'Tente uma busca diferente',
    'noArchivedLists': 'Nenhuma lista arquivada',
    'emptyList': 'Lista vazia',
    'emptySearch': 'Busca vazia',
    
    // Actions and buttons
    'createNew': 'Criar Novo',
    'addNew': 'Adicionar Novo',
    'saveChanges': 'Salvar Alterações',
    'discardChanges': 'Descartar Alterações',
    'apply': 'Aplicar',
    'reset': 'Redefinir',
    'clear': 'Limpar',
    'refresh': 'Atualizar',
    'reload': 'Recarregar',
    'retry': 'Tentar Novamente',
    'continue': 'Continuar',
    'finish': 'Finalizar',
    'done': 'Concluído',
    'ok': 'OK',
    'yes': 'Sim',
    'no': 'Não',
    'maybe': 'Talvez',
    'always': 'Sempre',
    'never': 'Nunca',
    'enable': 'Ativar',
    'disable': 'Desativar',
    'show': 'Mostrar',
    'hide': 'Ocultar',
    'expand': 'Expandir',
    'collapse': 'Recolher',
    'minimize': 'Minimizar',
    'maximize': 'Maximizar',
    'fullscreen': 'Tela Cheia',
    'exitFullscreen': 'Sair da Tela Cheia',
    
    // Time and dates
    'today': 'Hoje',
    'yesterday': 'Ontem',
    'tomorrow': 'Amanhã',
    'thisWeek': 'Esta Semana',
    'lastWeek': 'Semana Passada',
    'nextWeek': 'Próxima Semana',
    'thisMonth': 'Este Mês',
    'lastMonth': 'Mês Passado',
    'nextMonth': 'Próximo Mês',
    'thisYear': 'Este Ano',
    'lastYear': 'Ano Passado',
    'nextYear': 'Próximo Ano',
    'now': 'Agora',
    'later': 'Mais tarde',
    'soon': 'Em breve',
    'overdue': 'Atrasado',
    'upcoming': 'Próximos',
    'deadline': 'Prazo',
    'reminder': 'Lembrete',
    'schedule': 'Agendar',
    
    // Colors and appearance
    'color': 'Cor',
    'colors': 'Cores',
    'appearance': 'Aparência',
    'style': 'Estilo',
    'layout': 'Layout',
    'view': 'Visualização',
    'grid': 'Grade',
    'list': 'Lista',
    'card': 'Cartão',
    'table': 'Tabela',
    'compact': 'Compacto',
    'comfortable': 'Confortável',
    'spacious': 'Espaçoso',
    
    // Placeholders
    'searchPlaceholder': 'Digite para buscar...',
    'titlePlaceholder': 'Digite o título...',
    'descriptionPlaceholder': 'Digite a descrição...',
    'namePlaceholder': 'Digite seu nome...',
    'emailPlaceholder': 'Digite seu e-mail...',
    'passwordPlaceholder': 'Digite sua senha...',
    'messagePlaceholder': 'Digite sua mensagem...',
    'commentPlaceholder': 'Digite seu comentário...',
    'tagPlaceholder': 'Digite as tags...',
    'urlPlaceholder': 'Digite a URL...',
    'phonePlaceholder': 'Digite seu telefone...',
    'addressPlaceholder': 'Digite seu endereço...',
    
    // Sticky Notes
    'stickyNotes': 'Notas Adesivas',
    'notes.title': 'Notas',
    'notes.searchPlaceholder': 'Buscar notas...',
    'notes.noNotesCreate': 'Criar primeira nota',
    'notes.color': 'Cor',
    'notes.colorLabel': 'Cor da Nota',
    'notes.titleLabel': 'Título',
    'notes.contentLabel': 'Conteúdo',
    'notes.titlePlaceholder': 'Digite o título da nota...',
    'notes.contentPlaceholder': 'Escreva sua nota...',
    'notes.cancel': 'Cancelar',
    'notes.saveChanges': 'Salvar Alterações',
    'notes.delete': 'Excluir',
    'notes.editNote': 'Editar Nota',
    'searchNotes': 'Buscar notas...',
    'type': 'Tipo',
    'typeItem': 'Digite o item...',
    'clickToEdit': 'Clique para editar',
    'reloadApp': 'Recarregar App',
    'toolsAndStats': 'Ferramentas e Estatísticas',
    'appSettings': 'Configurações do App',
    'mainTaskList': 'Lista Principal de Tarefas',
    'createNewListSection': 'Seção Criar Nova Lista',
    
    // Missing translations
    'Digite o título...': 'Digite o título...',
    'Título (opcional)': 'Título (opcional)',
    'Escreva sua nota...': 'Escreva sua nota...',
    'Título da lista': 'Título da lista',
    'Item': 'Item',
    'Adicionar item': 'Adicionar item',
    'Nome da categoria': 'Nome da categoria',
    'Ou escolha uma existente:': 'Ou escolha uma existente:',
    'Salvar': 'Salvar',
    'Post-it salvo com sucesso!': 'Post-it salvo com sucesso!'
  },
  en: {
    // Basic
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'export': 'Export',
    'import': 'Import',
    'settings': 'Settings',
    'help': 'Help',
    'about': 'About',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    
    // App specific
    'appName': 'QuickList',
    'homescreen': 'Home',
    'allLists': 'All Lists',
    'newList': 'New List',
    'createList': 'Create List',
    'addList': 'Add List',
    'editList': 'Edit List',
    'deleteList': 'Delete List',
    'listTitle': 'List Title',
    'listDescription': 'List Description',
    'listColor': 'List Color',
    'noLists': 'No lists created',
    'noListsDesc': 'Create your first list to start organizing your tasks.',
    'listNotFound': 'List not found',
    'backToLists': 'Back to Lists',
    'searchLists': 'Search lists',
    'showArchived': 'Show Archived',
    'hideArchived': 'Hide Archived',
    'archiveList': 'Archive List',
    'unarchiveList': 'Unarchive List',
    'duplicateList': 'Duplicate List',
    'shareList': 'Share List',
    'listCopied': 'List copied to clipboard',
    'linkCopied': 'Link copied to clipboard',
    'listShared': 'List shared successfully',
    'listUpdated': 'List updated successfully',
    'listCreated': 'List created successfully',
    'listDeleted': 'List deleted successfully',
    'listArchived': 'List archived successfully',
    'listUnarchived': 'List unarchived successfully',
    'listDuplicated': 'List duplicated successfully',
    
    // Items
    'addItem': 'Add Item',
    'newItem': 'New Item',
    'editItem': 'Edit Item',
    'deleteItem': 'Delete Item',
    'itemText': 'Item Text',
    'itemAdded': 'Item added',
    'itemRemoved': 'Item removed',
    'itemUpdated': 'Item updated',
    'itemMoved': 'Item moved',
    'completedItem': '✓',
    'pendingItem': '○',
    'noItems': 'No items',
    'addItemHere': 'Add items here...',
    'addItemPlaceholder': 'Enter item text...',
    'searchTasks': 'Search tasks...',
    'searchTasksPlaceholder': 'Type to search...',
    'pending': 'Pending',
    'completed': 'Completed',
    'completedItemsRemoved': 'completed items removed',
    'markComplete': 'Mark as complete',
    'markIncomplete': 'Mark as incomplete',
    'priority': 'Priority',
    'dueDate': 'Due Date',
    'category': 'Category',
    'categories': 'Categories',
    'notes': 'Notes',
    'filters': 'Filters',
    'sortBy': 'Sort by',
    'recent': 'Recent',
    'alphabetical': 'Alphabetical',
    'completedSort': 'Completed',
    'showCompleted': 'Show completed',
    'hideCompleted': 'Hide completed',
    'clearCompleted': 'Clear completed',
    'selectAll': 'Select all',
    'deselectAll': 'Deselect all',
    
    // Statistics and insights
    'insights': 'Insights',
    'statistics': 'Statistics',
    'achievements': 'Achievements',
    'totalLists': 'Total Lists',
    'totalItems': 'Total Items',
    'completedItems': 'Completed Items',
    'pendingItems': 'Pending Items',
    'completionRate': 'Completion Rate',
    'productivity': 'Productivity',
    'streak': 'Streak',
    'longestStreak': 'Longest Streak',
    'currentStreak': 'Current Streak',
    'averageCompletion': 'Average Completion',
    'dailyGoal': 'Daily Goal',
    'weeklyGoal': 'Weekly Goal',
    'monthlyGoal': 'Monthly Goal',
    
    // Templates
    'templates': 'Templates',
    'useTemplate': 'Use Template',
    'selectTemplate': 'Select Template',
    'personalTemplate': 'Personal',
    'workTemplate': 'Work',
    'shoppingTemplate': 'Shopping',
    'travelTemplate': 'Travel',
    'customTemplate': 'Custom',
    'templateApplied': 'Template applied successfully',
    
    // UI Elements
    'homeScreen': 'Home Screen',
    'widget': 'Widget',
    'notification': 'Notification',
    'notifications': 'Notifications',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    'language': 'Language',
    'theme': 'Theme',
    'profile': 'Profile',
    'account': 'Account',
    'login': 'Login',
    'logout': 'Logout',
    'signup': 'Sign Up',
    'forgotPassword': 'Forgot Password',
    'resetPassword': 'Reset Password',
    'changePassword': 'Change Password',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'rememberMe': 'Remember Me',
    'stayLoggedIn': 'Stay Logged In',
    
    // Messages and feedback
    'welcomeMessage': 'Welcome to QuickList!',
    'errorMessage': 'An error occurred. Please try again.',
    'successMessage': 'Operation completed successfully!',
    'confirmDelete': 'Are you sure you want to delete?',
    'confirmArchive': 'Are you sure you want to archive?',
    'confirmClear': 'Are you sure you want to clear all completed items?',
    'noResultsFound': 'No results found',
    'tryDifferentSearch': 'Try a different search',
    'noArchivedLists': 'No archived lists',
    'emptyList': 'Empty list',
    'emptySearch': 'Empty search',
    
    // Actions and buttons
    'createNew': 'Create New',
    'addNew': 'Add New',
    'saveChanges': 'Save Changes',
    'discardChanges': 'Discard Changes',
    'apply': 'Apply',
    'reset': 'Reset',
    'clear': 'Clear',
    'refresh': 'Refresh',
    'reload': 'Reload',
    'retry': 'Retry',
    'continue': 'Continue',
    'finish': 'Finish',
    'done': 'Done',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'maybe': 'Maybe',
    'always': 'Always',
    'never': 'Never',
    'enable': 'Enable',
    'disable': 'Disable',
    'show': 'Show',
    'hide': 'Hide',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'minimize': 'Minimize',
    'maximize': 'Maximize',
    'fullscreen': 'Fullscreen',
    'exitFullscreen': 'Exit Fullscreen',
    
    // Time and dates
    'today': 'Today',
    'yesterday': 'Yesterday',
    'tomorrow': 'Tomorrow',
    'thisWeek': 'This Week',
    'lastWeek': 'Last Week',
    'nextWeek': 'Next Week',
    'thisMonth': 'This Month',
    'lastMonth': 'Last Month',
    'nextMonth': 'Next Month',
    'thisYear': 'This Year',
    'lastYear': 'Last Year',
    'nextYear': 'Next Year',
    'now': 'Now',
    'later': 'Later',
    'soon': 'Soon',
    'overdue': 'Overdue',
    'upcoming': 'Upcoming',
    'deadline': 'Deadline',
    'reminder': 'Reminder',
    'schedule': 'Schedule',
    
    // Colors and appearance
    'color': 'Color',
    'colors': 'Colors',
    'appearance': 'Appearance',
    'style': 'Style',
    'layout': 'Layout',
    'view': 'View',
    'grid': 'Grid',
    'list': 'List',
    'card': 'Card',
    'table': 'Table',
    'compact': 'Compact',
    'comfortable': 'Comfortable',
    'spacious': 'Spacious',
    
    // Placeholders
    'searchPlaceholder': 'Type to search...',
    'titlePlaceholder': 'Enter title...',
    'descriptionPlaceholder': 'Enter description...',
    'namePlaceholder': 'Enter your name...',
    'emailPlaceholder': 'Enter your email...',
    'passwordPlaceholder': 'Enter your password...',
    'messagePlaceholder': 'Enter your message...',
    'commentPlaceholder': 'Enter your comment...',
    'tagPlaceholder': 'Enter tags...',
    'urlPlaceholder': 'Enter URL...',
    'phonePlaceholder': 'Enter your phone...',
    'addressPlaceholder': 'Enter your address...',
    
    // Sticky Notes
    'stickyNotes': 'Sticky Notes',
    'notes.title': 'Notes',
    'notes.searchPlaceholder': 'Search notes...',
    'notes.noNotesCreate': 'Create first note',
    'notes.color': 'Color',
    'notes.colorLabel': 'Note Color',
    'notes.titleLabel': 'Title',
    'notes.contentLabel': 'Content',
    'notes.titlePlaceholder': 'Enter note title...',
    'notes.contentPlaceholder': 'Write your note...',
    'notes.cancel': 'Cancel',
    'notes.saveChanges': 'Save Changes',
    'notes.delete': 'Delete',
    'notes.editNote': 'Edit Note',
    'searchNotes': 'Search notes...',
    'type': 'Type',
    'typeItem': 'Type item...',
    'clickToEdit': 'Click to edit',
    'reloadApp': 'Reload App',
    'toolsAndStats': 'Tools and Stats',
    'appSettings': 'App Settings',
    'mainTaskList': 'Main Task List',
    'createNewListSection': 'Create New List Section',
    
    // Missing translations
    'Digite o título...': 'Enter title...',
    'Título (opcional)': 'Title (optional)',
    'Escreva sua nota...': 'Write your note...',
    'Título da lista': 'List title',
    'Item': 'Item',
    'Adicionar item': 'Add item',
    'Nome da categoria': 'Category name',
    'Ou escolha uma existente:': 'Or choose an existing one:',
    'Salvar': 'Save',
    'Post-it salvo com sucesso!': 'Post-it saved successfully!'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('quicklist-language') as Language;
    if (savedLanguage && (savedLanguage === 'pt' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('quicklist-language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    const translation = translations[language]?.[key];
    if (translation) {
      return translation;
    }
    
    // Fallback to Portuguese if key not found in current language
    if (language !== 'pt' && translations.pt[key]) {
      return translations.pt[key];
    }
    
    // Return key as fallback
    return key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language, 
    setLanguage: handleSetLanguage, 
    t
  }), [language, handleSetLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};